name: her_dt
channels:
  - defaults
dependencies:
  - python=3.6.13
  - pip:
      - absl-py==1.4.0
      - astor==0.8.1
      - beautifultable==1.1.0
      - cached-property==1.5.2
      - cffi==1.15.1
      - cloudpickle==1.2.2
      - cycler==0.11.0
      - cython==0.29.34
      - dataclasses==0.8
      - deap==1.3.3
      - dill==0.3.4
      - fasteners==0.18
      - future==0.18.3
      - gast==0.5.4
      - glfw==2.5.9
      - google-pasta==0.2.0
      - greenlet==2.0.2
      - grpcio==1.48.2
      - gym==0.15.4
      - h5py==3.1.0
      - imageio==2.15.0
      - importlib-metadata==4.8.3
      - joblib==1.1.1
      - keras-applications==1.0.8
      - keras-preprocessing==1.1.2
      - kiwisolver==1.3.1
      - markdown==3.3.7
      - matplotlib==3.3.4
      - mujoco-py==2.1.2.14
      - multiprocess==0.70.12.2
      - numpy==1.19.5
      - opencv-python==4.5.3.56
      - pathos==0.2.8
      - pillow==8.4.0
      - pip==21.3.1
      - pox==0.3.0
      - ppft==1.6.6.4
      - protobuf==3.19.6
      - pycparser==2.21
      - pyglet==1.3.2
      - pyparsing==3.0.9
      - python-dateutil==2.8.2
      - pyzmq==25.0.2
      - scipy==1.5.4
      - scoop==0.7.2.0
      - setuptools==59.6.0
      - six==1.16.0
      - tensorboard==1.14.0
      - tensorflow==1.14.0
      - tensorflow-estimator==1.14.0
      - termcolor==1.1.0
      - typing-extensions==4.1.1
      - wcwidth==0.2.6
      - werkzeug==2.0.3
      - wrapt==1.15.0
      - zipp==3.6.0
